# Generated by Django 5.0.3 on 2024-08-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('productid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
    ]
