# Generated by Django 5.0.3 on 2024-08-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.CharField(max_length=50)),
                ('userid', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
    ]
